spring:
  application:
    name: spring-ai-workshop

  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}

        chat:
          model: gemini-3.6-flash

        image:
          model: gemini-3.1-flash-image
          aspect-ratio: 1:1
          image-size: 1K

        embedding:
          api-key: ${GOOGLE_GENAI_API_KEY}
          text:
            model: gemini-embedding-2